services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: postgresql_ecommerce
    image: postgresql_ecommerce
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: ecommerce
    ports:
      - "5432:5432"
    volumes:
      - dimfact_pg_data:/var/lib/postgresql/data
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"
      - "-c"
      - "max_wal_senders=20"
      - "-c"
      - "max_replication_slots=20"
    networks:
      - dimfact-network

networks:
  dimfact-network:
    name: dimfact-network
    driver: bridge

volumes:
  dimfact_pg_data: