services:
  zookeeper:
    container_name: zookeeper
    image: zookeeper:3.9.3
    ports:
      - "2181:2181"
    environment:
      - ZOO_MY_ID=1
    networks:
      - dimfact-network

networks:
  dimfact-network:
    external: true